//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/Account")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/Account", IsNullable=false)]
    public partial class Account {
        
        private string profileNameField;
        
        private string emailField;
        
        private string passwordField;
        
        private string descriptionField;
        
        private string accountTypeField;
        
        private string accountConditionField;
        
        private int storageGBField;
        
        private int currentGBField;
        
        private long imageCountField;
        
        private AccountMachine[] machinesField;
        
        private long idField;
        
        private int versionField;
        
        public Account() {
            this.idField = ((long)(0));
            this.versionField = 0;
        }
        
        /// <remarks/>
        public string ProfileName {
            get {
                return this.profileNameField;
            }
            set {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCondition {
            get {
                return this.accountConditionField;
            }
            set {
                this.accountConditionField = value;
            }
        }
        
        /// <remarks/>
        public int StorageGB {
            get {
                return this.storageGBField;
            }
            set {
                this.storageGBField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentGB {
            get {
                return this.currentGBField;
            }
            set {
                this.currentGBField = value;
            }
        }
        
        /// <remarks/>
        public long ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Machine", IsNullable=false)]
        public AccountMachine[] Machines {
            get {
                return this.machinesField;
            }
            set {
                this.machinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/Account")]
    public partial class AccountMachine {
        
        private long idField;
        
        private int platformIdField;
        
        private bool platformIdFieldSpecified;
        
        private string nameField;
        
        private System.DateTime lastUsedField;
        
        private bool lastUsedFieldSpecified;
        
        private long tagIdField;
        
        private long categoryIdField;
        
        public AccountMachine() {
            this.idField = ((long)(0));
            this.tagIdField = ((long)(0));
            this.categoryIdField = ((long)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int platformId {
            get {
                return this.platformIdField;
            }
            set {
                this.platformIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool platformIdSpecified {
            get {
                return this.platformIdFieldSpecified;
            }
            set {
                this.platformIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime lastUsed {
            get {
                return this.lastUsedField;
            }
            set {
                this.lastUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUsedSpecified {
            get {
                return this.lastUsedFieldSpecified;
            }
            set {
                this.lastUsedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long tagId {
            get {
                return this.tagIdField;
            }
            set {
                this.tagIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
    }
}
