//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountStorage")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/AccountStorage", IsNullable=false)]
    public partial class AccountStorage {
        
        private string storageMessageField;
        
        private double storageGBLimitField;
        
        private int monthlyUploadCapField;
        
        private int uploadCount30DaysField;
        
        private double sizeGBField;
        
        private double compressedSizeGBField;
        
        private int imageCountField;
        
        private AccountStorageFormatRef[] formatRefField;
        
        private AccountStorageUploadSourceRef[] uploadSourceRefField;
        
        private AccountStorageImageYearRef[] imageYearRefField;
        
        private long idField;
        
        public AccountStorage() {
            this.idField = ((long)(0));
        }
        
        /// <remarks/>
        public string StorageMessage {
            get {
                return this.storageMessageField;
            }
            set {
                this.storageMessageField = value;
            }
        }
        
        /// <remarks/>
        public double StorageGBLimit {
            get {
                return this.storageGBLimitField;
            }
            set {
                this.storageGBLimitField = value;
            }
        }
        
        /// <remarks/>
        public int MonthlyUploadCap {
            get {
                return this.monthlyUploadCapField;
            }
            set {
                this.monthlyUploadCapField = value;
            }
        }
        
        /// <remarks/>
        public int UploadCount30Days {
            get {
                return this.uploadCount30DaysField;
            }
            set {
                this.uploadCount30DaysField = value;
            }
        }
        
        /// <remarks/>
        public double SizeGB {
            get {
                return this.sizeGBField;
            }
            set {
                this.sizeGBField = value;
            }
        }
        
        /// <remarks/>
        public double CompressedSizeGB {
            get {
                return this.compressedSizeGBField;
            }
            set {
                this.compressedSizeGBField = value;
            }
        }
        
        /// <remarks/>
        public int ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatRef")]
        public AccountStorageFormatRef[] FormatRef {
            get {
                return this.formatRefField;
            }
            set {
                this.formatRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UploadSourceRef")]
        public AccountStorageUploadSourceRef[] UploadSourceRef {
            get {
                return this.uploadSourceRefField;
            }
            set {
                this.uploadSourceRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageYearRef")]
        public AccountStorageImageYearRef[] ImageYearRef {
            get {
                return this.imageYearRefField;
            }
            set {
                this.imageYearRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountStorage")]
    public partial class AccountStorageFormatRef {
        
        private string formatField;
        
        private double sizeGBField;
        
        private double compressedSizeGBField;
        
        private int imageCountField;
        
        /// <remarks/>
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public double SizeGB {
            get {
                return this.sizeGBField;
            }
            set {
                this.sizeGBField = value;
            }
        }
        
        /// <remarks/>
        public double CompressedSizeGB {
            get {
                return this.compressedSizeGBField;
            }
            set {
                this.compressedSizeGBField = value;
            }
        }
        
        /// <remarks/>
        public int ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountStorage")]
    public partial class AccountStorageUploadSourceRef {
        
        private string nameField;
        
        private double sizeGBField;
        
        private double compressedSizeGBField;
        
        private int imageCountField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double SizeGB {
            get {
                return this.sizeGBField;
            }
            set {
                this.sizeGBField = value;
            }
        }
        
        /// <remarks/>
        public double CompressedSizeGB {
            get {
                return this.compressedSizeGBField;
            }
            set {
                this.compressedSizeGBField = value;
            }
        }
        
        /// <remarks/>
        public int ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountStorage")]
    public partial class AccountStorageImageYearRef {
        
        private string yearField;
        
        private double sizeGBField;
        
        private double compressedSizeGBField;
        
        private int imageCountField;
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public double SizeGB {
            get {
                return this.sizeGBField;
            }
            set {
                this.sizeGBField = value;
            }
        }
        
        /// <remarks/>
        public double CompressedSizeGB {
            get {
                return this.compressedSizeGBField;
            }
            set {
                this.compressedSizeGBField = value;
            }
        }
        
        /// <remarks/>
        public int ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }
    }
}
