//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/Account")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/Account", IsNullable=false)]
    public partial class Account {
        
        private string profileNameField;
        
        private string descField;
        
        private string emailField;
        
        private string passwordField;
        
        private int statusField;
        
        private int accountTypeField;
        
        private string accountTypeNameField;
        
        private System.DateTime openDateField;
        
        private System.DateTime closeDateField;
        
        private double storageGBLimitField;
        
        private double storageGBCurrentField;
        
        private int totalImagesField;
        
        private int monthlyUploadCapField;
        
        private int uploadCount30DaysField;
        
        private string keyField;
        
        private long idField;
        
        private int versionField;
        
        public Account() {
            this.idField = ((long)(0));
            this.versionField = 0;
        }
        
        /// <remarks/>
        public string ProfileName {
            get {
                return this.profileNameField;
            }
            set {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountTypeName {
            get {
                return this.accountTypeNameField;
            }
            set {
                this.accountTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OpenDate {
            get {
                return this.openDateField;
            }
            set {
                this.openDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
            }
        }
        
        /// <remarks/>
        public double StorageGBLimit {
            get {
                return this.storageGBLimitField;
            }
            set {
                this.storageGBLimitField = value;
            }
        }
        
        /// <remarks/>
        public double StorageGBCurrent {
            get {
                return this.storageGBCurrentField;
            }
            set {
                this.storageGBCurrentField = value;
            }
        }
        
        /// <remarks/>
        public int TotalImages {
            get {
                return this.totalImagesField;
            }
            set {
                this.totalImagesField = value;
            }
        }
        
        /// <remarks/>
        public int MonthlyUploadCap {
            get {
                return this.monthlyUploadCapField;
            }
            set {
                this.monthlyUploadCapField = value;
            }
        }
        
        /// <remarks/>
        public int UploadCount30Days {
            get {
                return this.uploadCount30DaysField;
            }
            set {
                this.uploadCount30DaysField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}
