//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountActionSummary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/AccountActionSummary", IsNullable=false)]
    public partial class AccountActionSummary {
        
        private string actionField;
        
        private long actionIdField;
        
        private AccountActionSummaryAccountActionRef[] accountActionRefField;
        
        private AccountActionSummaryGalleryActionRef[] galleryActionRefField;
        
        private AccountActionSummaryUserAppRef[] userAppRefField;
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public long ActionId {
            get {
                return this.actionIdField;
            }
            set {
                this.actionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccountActionRef")]
        public AccountActionSummaryAccountActionRef[] AccountActionRef {
            get {
                return this.accountActionRefField;
            }
            set {
                this.accountActionRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GalleryActionRef")]
        public AccountActionSummaryGalleryActionRef[] GalleryActionRef {
            get {
                return this.galleryActionRefField;
            }
            set {
                this.galleryActionRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserAppRef")]
        public AccountActionSummaryUserAppRef[] UserAppRef {
            get {
                return this.userAppRefField;
            }
            set {
                this.userAppRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountActionSummary")]
    public partial class AccountActionSummaryAccountActionRef {
        
        private string actionDescField;
        
        private int numTimesField;
        
        private System.DateTime actionDateField;
        
        /// <remarks/>
        public string ActionDesc {
            get {
                return this.actionDescField;
            }
            set {
                this.actionDescField = value;
            }
        }
        
        /// <remarks/>
        public int NumTimes {
            get {
                return this.numTimesField;
            }
            set {
                this.numTimesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActionDate {
            get {
                return this.actionDateField;
            }
            set {
                this.actionDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountActionSummary")]
    public partial class AccountActionSummaryGalleryActionRef {
        
        private string galleryNameField;
        
        private string galleryDescField;
        
        private int viewTotalField;
        
        private int viewMonthField;
        
        /// <remarks/>
        public string GalleryName {
            get {
                return this.galleryNameField;
            }
            set {
                this.galleryNameField = value;
            }
        }
        
        /// <remarks/>
        public string GalleryDesc {
            get {
                return this.galleryDescField;
            }
            set {
                this.galleryDescField = value;
            }
        }
        
        /// <remarks/>
        public int ViewTotal {
            get {
                return this.viewTotalField;
            }
            set {
                this.viewTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ViewMonth {
            get {
                return this.viewMonthField;
            }
            set {
                this.viewMonthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountActionSummary")]
    public partial class AccountActionSummaryUserAppRef {
        
        private long userAppIdField;
        
        private string appNameField;
        
        private string platformField;
        
        private string machineNameField;
        
        private bool blockedField;
        
        private System.DateTime lastUsedField;
        
        private AccountActionSummaryUserAppRefUserAppActionRef[] userAppActionRefField;
        
        /// <remarks/>
        public long UserAppId {
            get {
                return this.userAppIdField;
            }
            set {
                this.userAppIdField = value;
            }
        }
        
        /// <remarks/>
        public string AppName {
            get {
                return this.appNameField;
            }
            set {
                this.appNameField = value;
            }
        }
        
        /// <remarks/>
        public string Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string MachineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUsed {
            get {
                return this.lastUsedField;
            }
            set {
                this.lastUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserAppActionRef")]
        public AccountActionSummaryUserAppRefUserAppActionRef[] UserAppActionRef {
            get {
                return this.userAppActionRefField;
            }
            set {
                this.userAppActionRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AccountActionSummary")]
    public partial class AccountActionSummaryUserAppRefUserAppActionRef {
        
        private string actionDescField;
        
        private int numTimesField;
        
        private System.DateTime actionDateField;
        
        /// <remarks/>
        public string ActionDesc {
            get {
                return this.actionDescField;
            }
            set {
                this.actionDescField = value;
            }
        }
        
        /// <remarks/>
        public int NumTimes {
            get {
                return this.numTimesField;
            }
            set {
                this.numTimesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActionDate {
            get {
                return this.actionDateField;
            }
            set {
                this.actionDateField = value;
            }
        }
    }
}
