//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/AppDetail")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/AppDetail", IsNullable=false)]
    public partial class AppDetail {
        
        private string appKeyField;
        
        private int appMajorVersionField;
        
        private int appMinorVersionField;
        
        private long appCRCField;
        
        private string platformOSField;
        
        private string platformTypeField;
        
        private int oSMajorVersionField;
        
        private int oSMinorVersionField;
        
        private long userAppIdField;
        
        /// <remarks/>
        public string AppKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        public int AppMajorVersion {
            get {
                return this.appMajorVersionField;
            }
            set {
                this.appMajorVersionField = value;
            }
        }
        
        /// <remarks/>
        public int AppMinorVersion {
            get {
                return this.appMinorVersionField;
            }
            set {
                this.appMinorVersionField = value;
            }
        }
        
        /// <remarks/>
        public long AppCRC {
            get {
                return this.appCRCField;
            }
            set {
                this.appCRCField = value;
            }
        }
        
        /// <remarks/>
        public string PlatformOS {
            get {
                return this.platformOSField;
            }
            set {
                this.platformOSField = value;
            }
        }
        
        /// <remarks/>
        public string PlatformType {
            get {
                return this.platformTypeField;
            }
            set {
                this.platformTypeField = value;
            }
        }
        
        /// <remarks/>
        public int OSMajorVersion {
            get {
                return this.oSMajorVersionField;
            }
            set {
                this.oSMajorVersionField = value;
            }
        }
        
        /// <remarks/>
        public int OSMinorVersion {
            get {
                return this.oSMinorVersionField;
            }
            set {
                this.oSMinorVersionField = value;
            }
        }
        
        /// <remarks/>
        public long UserAppId {
            get {
                return this.userAppIdField;
            }
            set {
                this.userAppIdField = value;
            }
        }
    }
}
