//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/GalleryOptions")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/GalleryOptions", IsNullable=false)]
    public partial class GalleryOptions {
        
        private GalleryOptionsPresentationRef[] presentationField;
        
        private GalleryOptionsStyleRef[] styleField;
        
        private System.DateTime lastChangedField;
        
        private bool lastChangedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PresentationRef", IsNullable=false)]
        public GalleryOptionsPresentationRef[] Presentation {
            get {
                return this.presentationField;
            }
            set {
                this.presentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StyleRef", IsNullable=false)]
        public GalleryOptionsStyleRef[] Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastChanged {
            get {
                return this.lastChangedField;
            }
            set {
                this.lastChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastChangedSpecified {
            get {
                return this.lastChangedFieldSpecified;
            }
            set {
                this.lastChangedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/GalleryOptions")]
    public partial class GalleryOptionsPresentationRef {
        
        private int presentationIdField;
        
        private bool presentationIdFieldSpecified;
        
        private string nameField;
        
        private string descriptionField;
        
        private string jspNameField;
        
        private string cssExtensionField;
        
        private int maxSectionsField;
        
        private bool maxSectionsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int presentationId {
            get {
                return this.presentationIdField;
            }
            set {
                this.presentationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presentationIdSpecified {
            get {
                return this.presentationIdFieldSpecified;
            }
            set {
                this.presentationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jspName {
            get {
                return this.jspNameField;
            }
            set {
                this.jspNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cssExtension {
            get {
                return this.cssExtensionField;
            }
            set {
                this.cssExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxSections {
            get {
                return this.maxSectionsField;
            }
            set {
                this.maxSectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSectionsSpecified {
            get {
                return this.maxSectionsFieldSpecified;
            }
            set {
                this.maxSectionsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/GalleryOptions")]
    public partial class GalleryOptionsStyleRef {
        
        private int styleIdField;
        
        private bool styleIdFieldSpecified;
        
        private string nameField;
        
        private string descriptionField;
        
        private string cssFolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int styleId {
            get {
                return this.styleIdField;
            }
            set {
                this.styleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool styleIdSpecified {
            get {
                return this.styleIdFieldSpecified;
            }
            set {
                this.styleIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cssFolder {
            get {
                return this.cssFolderField;
            }
            set {
                this.cssFolderField = value;
            }
        }
    }
}
