//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/ImageIdList")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/ImageIdList", IsNullable=false)]
    public partial class ImageIdList {
        
        private long[] imageRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageRef")]
        public long[] ImageRef {
            get {
                return this.imageRefField;
            }
            set {
                this.imageRefField = value;
            }
        }
    }
}
