//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.fotowalla.com/UserApp")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.fotowalla.com/UserApp", IsNullable=false)]
    public partial class UserApp555 {
        
        private int platformIdField;
        
        private System.DateTime lastUsedField;
        
        private long tagIdField;
        
        private long categoryIdField;
        
        private long galleryIdField;
        
        private int thumbCacheSizeMBField;
        
        private int mainCopyCacheSizeMBField;
        
        private int imageFetchSizeField;
        
        private string mainCopyFolderField;
        
        private string autoUploadFolderField;
        
        private long idField;
        
        private int versionField;
        
        public UserApp555() {
            this.tagIdField = ((long)(0));
            this.categoryIdField = ((long)(0));
            this.galleryIdField = ((long)(0));
            this.idField = ((long)(0));
            this.versionField = 0;
        }
        
        /// <remarks/>
        public int PlatformId {
            get {
                return this.platformIdField;
            }
            set {
                this.platformIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LastUsed {
            get {
                return this.lastUsedField;
            }
            set {
                this.lastUsedField = value;
            }
        }
        
        /// <remarks/>
        public long TagId {
            get {
                return this.tagIdField;
            }
            set {
                this.tagIdField = value;
            }
        }
        
        /// <remarks/>
        public long CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public long GalleryId {
            get {
                return this.galleryIdField;
            }
            set {
                this.galleryIdField = value;
            }
        }
        
        /// <remarks/>
        public int ThumbCacheSizeMB {
            get {
                return this.thumbCacheSizeMBField;
            }
            set {
                this.thumbCacheSizeMBField = value;
            }
        }
        
        /// <remarks/>
        public int MainCopyCacheSizeMB {
            get {
                return this.mainCopyCacheSizeMBField;
            }
            set {
                this.mainCopyCacheSizeMBField = value;
            }
        }
        
        /// <remarks/>
        public int ImageFetchSize {
            get {
                return this.imageFetchSizeField;
            }
            set {
                this.imageFetchSizeField = value;
            }
        }
        
        /// <remarks/>
        public string MainCopyFolder {
            get {
                return this.mainCopyFolderField;
            }
            set {
                this.mainCopyFolderField = value;
            }
        }
        
        /// <remarks/>
        public string AutoUploadFolder {
            get {
                return this.autoUploadFolderField;
            }
            set {
                this.autoUploadFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}
