//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace ManageWalla {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/UploadStatusList")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/UploadStatusList", IsNullable=false)]
    public partial class UploadStatusList {
        
        private UploadStatusListImageUploadRef[] imageUploadRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageUploadRef")]
        public UploadStatusListImageUploadRef[] ImageUploadRef {
            get {
                return this.imageUploadRefField;
            }
            set {
                this.imageUploadRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/UploadStatusList")]
    public partial class UploadStatusListImageUploadRef {
        
        private long imageIdField;
        
        private bool imageIdFieldSpecified;
        
        private int imageStatusField;
        
        private bool imageStatusFieldSpecified;
        
        private string errorMessageField;
        
        private System.DateTime lastUpdatedField;
        
        private bool lastUpdatedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long imageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imageIdSpecified {
            get {
                return this.imageIdFieldSpecified;
            }
            set {
                this.imageIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int imageStatus {
            get {
                return this.imageStatusField;
            }
            set {
                this.imageStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imageStatusSpecified {
            get {
                return this.imageStatusFieldSpecified;
            }
            set {
                this.imageStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdatedSpecified {
            get {
                return this.lastUpdatedFieldSpecified;
            }
            set {
                this.lastUpdatedFieldSpecified = value;
            }
        }
    }
}
